x = rpois(2000, 100)
hist(x)
#h = hist(x,breaks=100)
range()
h = hist(x,breaks=seq(min(x), max(x) + 10, by = 10))
cols = rgb(h$counts, h$counts, h$counts, maxColorValue = max(h$counts))
hist(x,breaks=seq(min(x), max(x)+10, by = 10), col = cols)
#barplot(h$counts, col = cols)
#lines(density(x),col='blue')
d = density(x,from=min(x),to=max(x),bw=2)
lines(d$x,d$y*sum(h$counts)*(h$breaks[2]-h$breaks[1]),col='red')
#lines(0:100,90+sin(0:100/10)*10)
abline(v = mean(x),lty=2,col='red')
abline(v = median(x),lty=2,col='green')
abline(v = d$x[which.max(d$y)],lty=2,col='blue')

